### ISSUE TITLE
Tokenization removal reason

### ISSUE THREAD

**Issue by webmake** [hipay/hipay-fullservice-sdk-php#42]
Hello,
Why was decided to remove tokenization endpoints? I understand, generation and update can be fully performed via js library, but I'm talking about `requestLookupToken`, which provides usefull information about card. Should it be removed completely from api or is it mistake?

**Comment by legithubdeaymeric** [comment]
Hello,

This endpoint returns exactly the same data as a tokenization return (/ create).
If you need to make a "requestLookupToken" is you storing the token somewhere?
Why not store other information at the same time?
What is your use case?
This endpoint is not yet deprecated in the API but we advocate not to do more the call in server-to-server.

**Comment by jprotin** [comment]
Hi @webmake
 
Can you contact me by email ? jprotin@hipay.com
I'm french and we can continue in french by email ?

We need more informations because we don't understand exactly the usecase.

"_Storing can't be performed due PCI DSS_" : not exactly, I will explain you by email.

Many thanks.

Best.
Johan PROTIN

**Comment by jprotin** [comment]
We add token lookup method.

I close the issue.

**Comment by webmake** [comment]
Hello,

Why url has changed?

**Comment by jprotin** [comment]
Hi @webmake ,

The URL has changed :) All merchants received by email an important information about the URL of the tokenization changes to V2. the URL V1 is obsolet.

Thank you.

All the best.
